config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index', as: :home
  get 'tasks/new', to: 'tasks#new', as: :new_task
  post 'tasks', to: 'tasks#create', as: :tasks
  get '/tasks/:id', to: 'tasks#show', as: :task
  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy', as: :delete_task
  patch '/tasks/:id/completed', to: 'tasks#complete', as: :complete_task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @index = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to home_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  def complete
    @task = Task.find(params[:id])
    @task.completed = true
    @task.save
    redirect_to task_path(@task)
  end

  private

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/cba4ce51d7.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit your task</h1>
<div id="back">
<br><br><br>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <br>
  <%= f.text_field :title %>
<br>
  <%= f.label :details %>
  <br>
  <%= f.text_field :details %>
<br>
<div>
  <%= f.submit %>
</div class="card">
<% end %>
</div>

app/views/tasks/index.html.erb
<h1>To-do List</h1>
<div id="back">

  <div id="line">
    <% @index.each do |t| %>
      <p class="card"><%= link_to t.title, task_path(t) %></p>
    <% if t.completed == false %>
      <i class="far fa-square"></i>
    <% else %>
      <i class="far fa-check-square"></i>
    <% end %>
  <% end %>


    <div class="side">
      <h3><strong><%= link_to "add new task", new_task_path %></strong></h3>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>Add a new task busy bee</h1>
<div id="back">
  <br><br><br>
<form action="/tasks" method="post">
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <input type="text" name="task[title]" placeholder="task">
  <br>
  <input type="text" name="task[details]" placeholder="details">
  <br>
  <input type="submit" class="card">
</form>
</div>

app/views/tasks/show.html.erb
<div id="back">
  <br><br><br>
<h1 class="list" ><%= @task.title %></h1>
<h3 class="list" ><%= @task.details %></h3>

<div class="card">
  <% if @task.completed == false %>
    <p>Mark task as complete:</p>
    <%= link_to complete_task_path(@task), method: :patch do %>
      <i class="far fa-square" id="click"></i>
    <% end %>
  <% else %>
    <p>Completed!</p>
    <i class="far fa-check-square"></i>
  <% end %>
</div>

<div id="line" class="side">
<%= link_to "Home", home_path %>
</div>
<div id="line" class="side">
<%= link_to "Edit a task", edit_task_path %>
</div>
<div id="line" class="side">
<%= link_to "Delete", delete_task_path(@task), method: :delete %>
</div>
</div>